# Generated by Django 4.2.5 on 2024-08-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(default="Laptop", max_length=255),
        ),
    ]
